language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://lrae-mclauchlan.pact.dius.com.au/
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: "a/5wawntQXLXCCM/RO7GIxQLvXUqAeQs9kgjad6n6Az+OWTOJmE48CTmbbQy8jggMgZ7WsEMIEt/P5CAhF+dY9ZorkPqfJqn1pk4lu+NibCnOQGtMUNIiz4TTxWk4rt+bSQaP7LdTGb/uD7rC8qr6OisLYcwsbDVUyUxhNlzWuxT7FXc8IC/qswtWxxb+LN15rcAGBjx4ON6MXdnjfeI5hE7U/ICVSjucWf9OFmAwKO+MYCst6xNbcxN7192Dp+hV+eSmYcsuU3fQqJq24L42FZ8bkgnv4RRH8kOxAFUpflEMqQ8DTLpcM9MYLTphwBdPLmxI76qanVsJdzgqSWOaedTLjyD88P6MYby5Iruk/Ajw678jWtQ0V4gTF4702bNfbq7EuiU22Hu94hckTWMc/HLxMrcC71ZCEaoxyG61CG1hXxigDMdhkN6FlwR0vECzyV1oafUCfYHTBbzSvn0tfZehzEdQCw0LA3cgjFLcTkx0El88kJ+5XvUCcJcIPz/tecgeMsxhy7OpbYQn38EtBVJ/h46J+8/ZhfrNaS/PW5c5TC8zYFap+Z+p1CbPth7DYCRTjHQOJXjyL5Z/Bnri6+uX2INKXDgjGLli6mhP0/UMZc3BlhMakqll/w04qjtoOg0jR0Jw4ID3k3FESz9hJew7cCBiyxehftI2EaxPcs="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
